### ISSUE TITLE
May want

### ISSUE THREAD

**Issue by ghost** [DotNetRussell/MinerInTheMiddle#1]
May want to take a little look over it again and fix the errors that you left in there. otherwise, good idea.

**Comment by DotNetRussell** [comment]
Can you be more specific?

**Comment by ghost** [comment]
I will fork and correct as so many to list. simpler this was as I already fixed all.

**Comment by DotNetRussell** [comment]
I'm closing this issue because reporter failed to provide details or steps to recreate.

**Comment by ghost** [comment]
then fix yourself. not at all bothered. it is a mess completely. never mind better things to do.
